/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:83a899d1-ed2c-47cb-b195-d155edbc83ea",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gEHizsIqJ",
    "aws_user_pools_web_client_id": "6vh60l53h5odmth23cvhujhm8t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://p3nuwfnom5cunbr4qz5gofgdwi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
